version: '3.7'

services:
  judge0-server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./tmp/srv/jailer/1:/tmp:exec
    privileged: true
    ports:
      - "2358:2358"
    environment:
      - REDIS_URL=redis://judge0-redis:6379
      - POSTGRES_HOST=judge0-db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=YourJudge0Password
    depends_on:
      - judge0-db
      - judge0-redis
    restart: unless-stopped

  judge0-workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./tmp/srv/jailer/1:/tmp:exec
    privileged: true
    environment:
      - REDIS_URL=redis://judge0-redis:6379
      - POSTGRES_HOST=judge0-db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=YourJudge0Password
    depends_on:
      - judge0-db
      - judge0-redis
    restart: unless-stopped

  judge0-db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - judge0-db-data:/var/lib/postgresql/data/
    restart: unless-stopped

  judge0-redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - judge0-redis-data:/data
    restart: unless-stopped

volumes:
  judge0-db-data:
  judge0-redis-data:
